trigger:
  - development

pool:
  vmImage: 'windows-2019'

stages:
  - stage: BUILD_AND_TEST
    jobs:
      - job: BUILD_AND_TEST
        steps:
        - task: Npm@1
          inputs:
            command: 'ci'
            workingDir: 'spa-client'
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: 'spa-client'
            customCommand: 'run lint'
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: 'spa-client'
            customCommand: 'run build'
