trigger:
  branches:
    include:
      - master
      - assignment/*
      - solution/*

pool:
  vmImage: "windows-2019"

stages:
  - stage: STAGE_NAME
    displayName: PRETTY_STAGE_NAME
    jobs:
      - job: ECHO
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo Hello world
                echo Hello universe
