trigger:
  - master
  - assignment/*
  - solution/*

pool:
  vmImage: "windows-2019"

stages:
  - stage: BUILD_STAGE
    displayName: BUILD
    jobs:
      - job: CI
        steps:
        - task: Npm@1
          inputs:
            command: 'ci'
            workingDir: 'spa-client'
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: 'spa-client'
            customCommand: 'run build'
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: 'spa-client'
            customCommand: 'run export'